"""
SHACL Shape Generator

Uses LLMs to generate SHACL shapes for ontology mapping validation.
"""

import asyncio
from dataclasses import dataclass
from typing import Optional

from rdflib import Graph

from src.llm.client import LLMClient, create_llm_client
from src.llm.prompts import SYSTEM_PROMPT, SHACL_SUGGESTION_PROMPT, format_prompt
from src.llm.parsers import SHACLSuggestionResponse, parse_shacl_response


@dataclass
class GeneratedShape:
    """A SHACL shape generated by the LLM."""
    name: str
    description: str
    turtle: str
    rationale: str


class ShapeGenerator:
    """
    Generates SHACL shapes using LLM assistance.
    
    Analyzes ontology patterns and mapping requirements to suggest
    appropriate validation constraints.
    """
    
    def __init__(self, llm_client: Optional[LLMClient] = None):
        """
        Initialize the shape generator.
        
        Args:
            llm_client: Optional LLM client
        """
        self.llm = llm_client or create_llm_client()
    
    async def generate_shapes(
        self,
        domain_description: str,
        sample_mappings: list[dict],
        common_issues: list[str] = None,
    ) -> list[GeneratedShape]:
        """
        Generate SHACL shapes based on domain and mapping patterns.
        
        Args:
            domain_description: Description of the ontology domain
            sample_mappings: List of sample mappings with structure
            common_issues: Known issues to address
            
        Returns:
            List of generated SHACL shapes
        """
        # Format sample mappings for the prompt
        mappings_str = self._format_sample_mappings(sample_mappings)
        issues_str = "\n".join(f"- {issue}" for issue in (common_issues or []))
        
        if not issues_str:
            issues_str = """
- Missing required metadata on mappings
- Invalid IRI formats
- Confidence scores out of range
- Inconsistent predicate usage
"""
        
        prompt = format_prompt(
            SHACL_SUGGESTION_PROMPT,
            domain_description=domain_description,
            sample_mappings=mappings_str,
            common_issues=issues_str,
        )
        
        response = await self.llm.complete_with_system(
            system=SYSTEM_PROMPT,
            user=prompt,
        )
        
        parsed = parse_shacl_response(response.content)
        
        shapes = []
        for shape in parsed.shapes:
            shapes.append(GeneratedShape(
                name=shape.name,
                description=shape.description,
                turtle=shape.turtle,
                rationale=parsed.rationale,
            ))
        
        return shapes
    
    async def generate_shapes_for_ontology(
        self,
        ontology_graph: Graph,
        mapping_graph: Optional[Graph] = None,
    ) -> list[GeneratedShape]:
        """
        Analyze an ontology and generate appropriate SHACL shapes.
        
        Args:
            ontology_graph: The ontology to analyze
            mapping_graph: Optional existing mappings to analyze
            
        Returns:
            List of generated shapes
        """
        # Extract domain information from ontology
        domain_info = self._extract_domain_info(ontology_graph)
        
        # Extract sample mappings if provided
        sample_mappings = []
        if mapping_graph:
            sample_mappings = self._extract_sample_mappings(mapping_graph)
        
        return await self.generate_shapes(
            domain_description=domain_info,
            sample_mappings=sample_mappings,
        )
    
    def _format_sample_mappings(self, mappings: list[dict]) -> str:
        """Format sample mappings for the prompt."""
        if not mappings:
            return "No sample mappings provided."
        
        lines = []
        for i, mapping in enumerate(mappings[:5], 1):  # Limit to 5 samples
            source = mapping.get("source", "unknown")
            target = mapping.get("target", "unknown")
            predicate = mapping.get("predicate", "skos:exactMatch")
            lines.append(f"{i}. {source} --[{predicate}]--> {target}")
        
        return "\n".join(lines)
    
    def _extract_domain_info(self, graph: Graph) -> str:
        """Extract domain description from ontology."""
        from rdflib.namespace import RDF, RDFS, OWL, DC, DCTERMS
        
        # Try to find ontology metadata
        descriptions = []
        
        # Look for ontology IRI and description
        for ont in graph.subjects(RDF.type, OWL.Ontology):
            for desc in graph.objects(ont, RDFS.comment):
                descriptions.append(str(desc))
            for desc in graph.objects(ont, DCTERMS.description):
                descriptions.append(str(desc))
        
        # Count classes and properties
        class_count = len(list(graph.subjects(RDF.type, OWL.Class)))
        prop_count = len(list(graph.subjects(RDF.type, OWL.ObjectProperty)))
        
        if descriptions:
            base_desc = descriptions[0][:500]
        else:
            base_desc = "Ontology domain information not available"
        
        return f"""{base_desc}

Statistics:
- Classes: {class_count}
- Object Properties: {prop_count}
"""
    
    def _extract_sample_mappings(self, graph: Graph, limit: int = 5) -> list[dict]:
        """Extract sample mappings from a mapping graph."""
        from rdflib.namespace import OWL, SKOS
        
        samples = []
        predicates = [
            OWL.equivalentClass,
            SKOS.exactMatch,
            SKOS.closeMatch,
            SKOS.broadMatch,
            SKOS.narrowMatch,
        ]
        
        for pred in predicates:
            for subj, obj in graph.subject_objects(pred):
                if len(samples) >= limit:
                    break
                samples.append({
                    "source": str(subj),
                    "target": str(obj),
                    "predicate": str(pred).split("#")[-1] if "#" in str(pred) else str(pred).split("/")[-1],
                })
        
        return samples
    
    def validate_generated_shape(self, turtle: str) -> tuple[bool, str]:
        """
        Validate that generated SHACL is syntactically correct.
        
        Args:
            turtle: SHACL shape in Turtle format
            
        Returns:
            Tuple of (is_valid, error_message)
        """
        try:
            g = Graph()
            g.parse(data=turtle, format="turtle")
            return True, ""
        except Exception as e:
            return False, str(e)
    
    async def generate_and_validate(
        self,
        domain_description: str,
        sample_mappings: list[dict],
        common_issues: list[str] = None,
        max_retries: int = 2,
    ) -> list[GeneratedShape]:
        """
        Generate shapes and validate them, retrying if needed.
        
        Args:
            domain_description: Description of the domain
            sample_mappings: Sample mappings
            common_issues: Issues to address
            max_retries: Maximum retry attempts for invalid shapes
            
        Returns:
            List of validated shapes
        """
        shapes = await self.generate_shapes(
            domain_description, sample_mappings, common_issues
        )
        
        validated = []
        for shape in shapes:
            is_valid, error = self.validate_generated_shape(shape.turtle)
            
            if is_valid:
                validated.append(shape)
            else:
                # Could implement retry logic here
                print(f"Warning: Generated shape '{shape.name}' is invalid: {error}")
        
        return validated


# Predefined shape templates for common patterns
SHAPE_TEMPLATES = {
    "mapping_metadata": """
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix sssom: <https://w3id.org/sssom/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

sssom:MappingMetadataShape a sh:NodeShape ;
    sh:targetClass sssom:Mapping ;
    sh:property [
        sh:path sssom:subject_id ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:nodeKind sh:IRI ;
    ] ;
    sh:property [
        sh:path sssom:object_id ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
        sh:nodeKind sh:IRI ;
    ] ;
    sh:property [
        sh:path sssom:predicate_id ;
        sh:minCount 1 ;
        sh:maxCount 1 ;
    ] .
""",
    
    "confidence_range": """
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix sssom: <https://w3id.org/sssom/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

sssom:ConfidenceShape a sh:NodeShape ;
    sh:targetSubjectsOf sssom:confidence ;
    sh:property [
        sh:path sssom:confidence ;
        sh:datatype xsd:decimal ;
        sh:minInclusive 0.0 ;
        sh:maxInclusive 1.0 ;
        sh:message "Confidence must be between 0.0 and 1.0" ;
    ] .
""",
    
    "iri_pattern": """
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

ex:ValidIRIShape a sh:NodeShape ;
    sh:targetSubjectsOf owl:equivalentClass, skos:exactMatch, skos:closeMatch ;
    sh:nodeKind sh:IRI ;
    sh:pattern "^https?://" ;
    sh:message "Mapping subjects must be valid HTTP(S) IRIs" .
""",
}


def get_template_shape(template_name: str) -> str:
    """Get a predefined shape template by name."""
    return SHAPE_TEMPLATES.get(template_name, "")


async def generate_shapes_for_domain(
    domain: str,
    samples: list[dict] = None,
) -> list[GeneratedShape]:
    """
    Convenience function to generate shapes for a domain.
    
    Args:
        domain: Domain description
        samples: Optional sample mappings
        
    Returns:
        List of generated shapes
    """
    generator = ShapeGenerator()
    return await generator.generate_shapes(
        domain_description=domain,
        sample_mappings=samples or [],
    )
